# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-23 18:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='registertime',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 23, 18, 29, 19, 652708)),
        ),
    ]
