# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-07 17:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171223_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128)),
                ('isRead', models.BooleanField(default=False)),
                ('publishtime', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='registertime',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 7, 17, 18, 42, 663375)),
        ),
        migrations.AddField(
            model_name='infomessage',
            name='attachUser',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.Users'),
        ),
    ]
