# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-23 18:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='createdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 23, 18, 29, 19, 661643), verbose_name='Create time'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 23, 18, 29, 19, 661668), verbose_name='Modify time'),
        ),
    ]
