# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-23 19:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20171223_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='commentcount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='createdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 23, 19, 43, 58, 433849), verbose_name='Create time'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 23, 19, 43, 58, 433872), verbose_name='Modify time'),
        ),
    ]
